# -*- coding: utf-8 -*-
"""2_Exploration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IB-reSgx9f0wHPAOlDdV8sSkF0Dam8Xk

Author: Amitabh Chakravorty

DATA EXPLORATION - Understanding Dataset Structure
"""

# ============================================================================
# SETUP
# ============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from google.colab import drive

# Mount drive
drive.mount('/content/drive')
base_path = '/content/drive/MyDrive/cryptojacking_validation'
os.chdir(base_path)

print("Working directory:", os.getcwd())

# ============================================================================
# EXPLORE DS2OS DATASET
# ============================================================================

print("\n")
print("DS2OS DATASET EXPLORATION")
print("\n")

# List files in DS2OS directory
ds2os_path = 'data/raw/ds2os'
ds2os_files = os.listdir(ds2os_path)
print(f"\nFiles in ds2os directory:")
for f in ds2os_files:
    print(f"  - {f}")

# Find CSV files
csv_files = [f for f in ds2os_files if f.endswith('.csv')]
print(f"\nCSV files found: {csv_files}")

# Load the first CSV file
if csv_files:
    df_ds2os = pd.read_csv(f'{ds2os_path}/{csv_files[0]}')

    print(f"\n Dataset Shape: {df_ds2os.shape}")
    print(f"   Rows: {df_ds2os.shape[0]:,}")
    print(f"   Columns: {df_ds2os.shape[1]}")

    print(f"\n Column Names:")
    for i, col in enumerate(df_ds2os.columns, 1):
        print(f"   {i:2d}. {col}")

    print(f"\n First 5 Rows:")
    print(df_ds2os.head())

    print(f"\n Data Types:")
    print(df_ds2os.dtypes)

    print(f"\n Missing Values:")
    missing = df_ds2os.isnull().sum()
    if missing.sum() > 0:
        print(missing[missing > 0])
    else:
        print("   No missing values ✓")

    print(f"\n Potential Target Columns:")
    target_keywords = ['label', 'class', 'target', 'attack', 'type', 'category']
    potential_targets = [col for col in df_ds2os.columns
                        if any(keyword in col.lower() for keyword in target_keywords)]

    if potential_targets:
        print(f"   Found: {potential_targets}")
        for col in potential_targets:
            print(f"\n   Distribution of '{col}':")
            print(df_ds2os[col].value_counts())

            # Plot distribution
            plt.figure(figsize=(10, 4))
            df_ds2os[col].value_counts().plot(kind='bar')
            plt.title(f"DS2OS - Distribution of '{col}'")
            plt.xlabel(col)
            plt.ylabel('Count')
            plt.xticks(rotation=45, ha='right')
            plt.tight_layout()
            plt.savefig(f'results/figures/ds2os_{col}_distribution.png', dpi=300, bbox_inches='tight')
            plt.show()
    else:
        print("No obvious target column found!")
        print("Please manually identify the target column")

else:
    print("No CSV files found in DS2OS directory")

# ============================================================================
# EXPLORE NSL-KDD DATASET
# ============================================================================

print("\n\n" + "="*70)
print("NSL-KDD DATASET EXPLORATION")
print("="*70)

nsl_path = 'data/raw/nsl_kdd'
nsl_files = os.listdir(nsl_path)
print(f"\nFiles in nsl_kdd directory:")
for f in nsl_files:
    print(f"  - {f}")

# NSL-KDD often has specific file names
train_files = [f for f in nsl_files if 'train' in f.lower() and (f.endswith('.csv') or f.endswith('.txt'))]
test_files = [f for f in nsl_files if 'test' in f.lower() and (f.endswith('.csv') or f.endswith('.txt'))]

print(f"\nTrain files: {train_files}")
print(f"Test files: {test_files}")

# NSL-KDD standard column names (may not have header)
nsl_columns = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes',
    'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
    'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
    'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
    'num_access_files', 'num_outbound_cmds', 'is_host_login',
    'is_guest_login', 'count', 'srv_count', 'serror_rate',
    'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
    'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
    'dst_host_srv_count', 'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
    'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate', 'label', 'difficulty'
]

if train_files:
    try:
        # Try loading with headers first
        df_nsl = pd.read_csv(f'{nsl_path}/{train_files[0]}', nrows=1000)
        print(f"\n Dataset loaded with headers")
    except:
        # If no headers, use standard NSL-KDD columns
        df_nsl = pd.read_csv(f'{nsl_path}/{train_files[0]}', names=nsl_columns, nrows=1000)
        print(f"\n Dataset loaded without headers (using standard NSL-KDD columns)")

    print(f"   Shape: {df_nsl.shape}")

    print(f"\n Column Names:")
    for i, col in enumerate(df_nsl.columns, 1):
        print(f"   {i:2d}. {col}")

    print(f"\n First 5 Rows:")
    print(df_nsl.head())

    print(f"\n Label Distribution:")
    if 'label' in df_nsl.columns:
        print(df_nsl['label'].value_counts())

        # Plot
        plt.figure(figsize=(12, 5))
        df_nsl['label'].value_counts().plot(kind='bar')
        plt.title('NSL-KDD - Attack Type Distribution')
        plt.xlabel('Attack Type')
        plt.ylabel('Count')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.savefig('results/figures/nsl_kdd_label_distribution.png', dpi=300, bbox_inches='tight')
        plt.show()

        # Binary classification
        df_nsl['is_attack'] = df_nsl['label'].apply(lambda x: 0 if x == 'normal' else 1)
        print(f"\n Binary Classification (Normal vs Attack):")
        print(df_nsl['is_attack'].value_counts())

# ============================================================================
# SUMMARY
# ============================================================================

print("\n\n" + "="*70)
print("EXPLORATION SUMMARY & NEXT STEPS")
print("="*70)

exploration_summary = {
    'ds2os_file': csv_files[0] if csv_files else 'NOT_FOUND',
    'ds2os_target_columns': potential_targets if potential_targets else 'MANUALLY_IDENTIFY',
    'nsl_train_file': train_files[0] if train_files else 'NOT_FOUND',
    'nsl_test_file': test_files[0] if test_files else 'NOT_FOUND',
}

print("\n Exploration Results:")
for key, value in exploration_summary.items():
    print(f"   {key}: {value}")

# Save summary
import json
with open('results/exploration_summary.json', 'w') as f:
    json.dump(exploration_summary, f, indent=2)

print("\n Exploration complete!")
print(" Summary saved to: results/exploration_summary.json")
print("\n Next: Run the preprocessing notebook")